version: "3.5"

services:
  mongo:
    image: mongo

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    links:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
