name: Docker Publish

on:
  push:
    branches:
      - master  # Replace with your branch name

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t docker.pkg.github.com/tuanvupresent/test/image-name:${{ github.sha }} .
        docker push docker.pkg.github.com/tuanvupresent/test/image-name:${{ github.sha }}
